inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-rspec
  - rubocop-rake

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/NestedGroups:
  Max: 4
